services:
  - type: web
    name: smartfarm-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
